/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AccountV2StepModel model module.
 * @module model/AccountV2StepModel
 * @version 1.0
 */
class AccountV2StepModel {
    /**
     * Constructs a new <code>AccountV2StepModel</code>.
     * Model containing data about the account step for a lead
     * @alias module:model/AccountV2StepModel
     */
    constructor() { 
        
        AccountV2StepModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AccountV2StepModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountV2StepModel} obj Optional instance to populate.
     * @return {module:model/AccountV2StepModel} The populated <code>AccountV2StepModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountV2StepModel();

            if (data.hasOwnProperty('leadId')) {
                obj['leadId'] = ApiClient.convertToType(data['leadId'], 'String');
            }
            if (data.hasOwnProperty('sortCode')) {
                obj['sortCode'] = ApiClient.convertToType(data['sortCode'], 'String');
            }
            if (data.hasOwnProperty('accountNumber')) {
                obj['accountNumber'] = ApiClient.convertToType(data['accountNumber'], 'String');
            }
            if (data.hasOwnProperty('swift')) {
                obj['swift'] = ApiClient.convertToType(data['swift'], 'String');
            }
            if (data.hasOwnProperty('iban')) {
                obj['iban'] = ApiClient.convertToType(data['iban'], 'String');
            }
            if (data.hasOwnProperty('bankName')) {
                obj['bankName'] = ApiClient.convertToType(data['bankName'], 'String');
            }
            if (data.hasOwnProperty('confirmedCompanyAccount')) {
                obj['confirmedCompanyAccount'] = ApiClient.convertToType(data['confirmedCompanyAccount'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the lead id for this account
 * @member {String} leadId
 */
AccountV2StepModel.prototype['leadId'] = undefined;

/**
 * Gets or sets the sort code for the account
 * @member {String} sortCode
 */
AccountV2StepModel.prototype['sortCode'] = undefined;

/**
 * Gets or sets the account number
 * @member {String} accountNumber
 */
AccountV2StepModel.prototype['accountNumber'] = undefined;

/**
 * Gets or sets the swift code for the account
 * @member {String} swift
 */
AccountV2StepModel.prototype['swift'] = undefined;

/**
 * Gets or sets the IBAN for the account
 * @member {String} iban
 */
AccountV2StepModel.prototype['iban'] = undefined;

/**
 * Gets or sets the name of the bank assoicated with the account
 * @member {String} bankName
 */
AccountV2StepModel.prototype['bankName'] = undefined;

/**
 * Gets or sets a value indicating whether the account is confirmed to be the company account
 * @member {Boolean} confirmedCompanyAccount
 */
AccountV2StepModel.prototype['confirmedCompanyAccount'] = undefined;






export default AccountV2StepModel;

