/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AccountDetailsModel model module.
 * @module model/AccountDetailsModel
 * @version 1.0
 */
class AccountDetailsModel {
    /**
     * Constructs a new <code>AccountDetailsModel</code>.
     * @alias module:model/AccountDetailsModel
     * @param sortCode {String} 
     * @param accountNumber {String} 
     * @param swift {String} 
     * @param iban {String} 
     * @param bankName {String} 
     * @param confirmedCompanyAccount {Boolean} 
     */
    constructor(sortCode, accountNumber, swift, iban, bankName, confirmedCompanyAccount) { 
        
        AccountDetailsModel.initialize(this, sortCode, accountNumber, swift, iban, bankName, confirmedCompanyAccount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sortCode, accountNumber, swift, iban, bankName, confirmedCompanyAccount) { 
        obj['sortCode'] = sortCode;
        obj['accountNumber'] = accountNumber;
        obj['swift'] = swift;
        obj['iban'] = iban;
        obj['bankName'] = bankName;
        obj['confirmedCompanyAccount'] = confirmedCompanyAccount;
    }

    /**
     * Constructs a <code>AccountDetailsModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountDetailsModel} obj Optional instance to populate.
     * @return {module:model/AccountDetailsModel} The populated <code>AccountDetailsModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountDetailsModel();

            if (data.hasOwnProperty('sortCode')) {
                obj['sortCode'] = ApiClient.convertToType(data['sortCode'], 'String');
            }
            if (data.hasOwnProperty('accountNumber')) {
                obj['accountNumber'] = ApiClient.convertToType(data['accountNumber'], 'String');
            }
            if (data.hasOwnProperty('swift')) {
                obj['swift'] = ApiClient.convertToType(data['swift'], 'String');
            }
            if (data.hasOwnProperty('iban')) {
                obj['iban'] = ApiClient.convertToType(data['iban'], 'String');
            }
            if (data.hasOwnProperty('bankName')) {
                obj['bankName'] = ApiClient.convertToType(data['bankName'], 'String');
            }
            if (data.hasOwnProperty('confirmedCompanyAccount')) {
                obj['confirmedCompanyAccount'] = ApiClient.convertToType(data['confirmedCompanyAccount'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} sortCode
 */
AccountDetailsModel.prototype['sortCode'] = undefined;

/**
 * @member {String} accountNumber
 */
AccountDetailsModel.prototype['accountNumber'] = undefined;

/**
 * @member {String} swift
 */
AccountDetailsModel.prototype['swift'] = undefined;

/**
 * @member {String} iban
 */
AccountDetailsModel.prototype['iban'] = undefined;

/**
 * @member {String} bankName
 */
AccountDetailsModel.prototype['bankName'] = undefined;

/**
 * @member {Boolean} confirmedCompanyAccount
 */
AccountDetailsModel.prototype['confirmedCompanyAccount'] = undefined;






export default AccountDetailsModel;

