/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateThirdPartyAdvanceOnboardingResultModel model module.
 * @module model/CreateThirdPartyAdvanceOnboardingResultModel
 * @version 1.0
 */
class CreateThirdPartyAdvanceOnboardingResultModel {
    /**
     * Constructs a new <code>CreateThirdPartyAdvanceOnboardingResultModel</code>.
     * The result of creating a third party lead
     * @alias module:model/CreateThirdPartyAdvanceOnboardingResultModel
     */
    constructor() { 
        
        CreateThirdPartyAdvanceOnboardingResultModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateThirdPartyAdvanceOnboardingResultModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateThirdPartyAdvanceOnboardingResultModel} obj Optional instance to populate.
     * @return {module:model/CreateThirdPartyAdvanceOnboardingResultModel} The populated <code>CreateThirdPartyAdvanceOnboardingResultModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateThirdPartyAdvanceOnboardingResultModel();

            if (data.hasOwnProperty('leadId')) {
                obj['leadId'] = ApiClient.convertToType(data['leadId'], 'String');
            }
            if (data.hasOwnProperty('leadURL')) {
                obj['leadURL'] = ApiClient.convertToType(data['leadURL'], 'String');
            }
            if (data.hasOwnProperty('signUpURL')) {
                obj['signUpURL'] = ApiClient.convertToType(data['signUpURL'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the Lead Id
 * @member {String} leadId
 */
CreateThirdPartyAdvanceOnboardingResultModel.prototype['leadId'] = undefined;

/**
 * Gets or sets the Lead redirect URL
 * @member {String} leadURL
 */
CreateThirdPartyAdvanceOnboardingResultModel.prototype['leadURL'] = undefined;

/**
 * Gets or sets the broker redirect URL
 * @member {String} signUpURL
 */
CreateThirdPartyAdvanceOnboardingResultModel.prototype['signUpURL'] = undefined;






export default CreateThirdPartyAdvanceOnboardingResultModel;

