/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DateModel model module.
 * @module model/DateModel
 * @version 1.0
 */
class DateModel {
    /**
     * Constructs a new <code>DateModel</code>.
     * Date Model
     * @alias module:model/DateModel
     * @param year {Number} Gets or sets Year
     * @param month {Number} Gets or sets Month
     * @param day {Number} Gets or sets Day
     */
    constructor(year, month, day) { 
        
        DateModel.initialize(this, year, month, day);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, year, month, day) { 
        obj['year'] = year;
        obj['month'] = month;
        obj['day'] = day;
    }

    /**
     * Constructs a <code>DateModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DateModel} obj Optional instance to populate.
     * @return {module:model/DateModel} The populated <code>DateModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DateModel();

            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('month')) {
                obj['month'] = ApiClient.convertToType(data['month'], 'Number');
            }
            if (data.hasOwnProperty('day')) {
                obj['day'] = ApiClient.convertToType(data['day'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets Year
 * @member {Number} year
 */
DateModel.prototype['year'] = undefined;

/**
 * Gets or sets Month
 * @member {Number} month
 */
DateModel.prototype['month'] = undefined;

/**
 * Gets or sets Day
 * @member {Number} day
 */
DateModel.prototype['day'] = undefined;






export default DateModel;

