/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Industry model module.
 * @module model/Industry
 * @version 1.0
 */
class Industry {
    /**
     * Constructs a new <code>Industry</code>.
     * Model representing an industry
     * @alias module:model/Industry
     */
    constructor() { 
        
        Industry.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Industry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Industry} obj Optional instance to populate.
     * @return {module:model/Industry} The populated <code>Industry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Industry();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the SIC code for the industry
 * @member {String} code
 */
Industry.prototype['code'] = undefined;

/**
 * Gets or sets the description of the industry
 * @member {String} description
 */
Industry.prototype['description'] = undefined;






export default Industry;

