/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import KycDocumentModel from './KycDocumentModel';
import SignificantPersonDocumentsModel from './SignificantPersonDocumentsModel';

/**
 * The KycDocumentsV2StepModel model module.
 * @module model/KycDocumentsV2StepModel
 * @version 1.0
 */
class KycDocumentsV2StepModel {
    /**
     * Constructs a new <code>KycDocumentsV2StepModel</code>.
     * Model containing data about the KYC document step
     * @alias module:model/KycDocumentsV2StepModel
     */
    constructor() { 
        
        KycDocumentsV2StepModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>KycDocumentsV2StepModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KycDocumentsV2StepModel} obj Optional instance to populate.
     * @return {module:model/KycDocumentsV2StepModel} The populated <code>KycDocumentsV2StepModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KycDocumentsV2StepModel();

            if (data.hasOwnProperty('companyDocuments')) {
                obj['companyDocuments'] = ApiClient.convertToType(data['companyDocuments'], {'String': KycDocumentModel});
            }
            if (data.hasOwnProperty('significantPersonDocuments')) {
                obj['significantPersonDocuments'] = ApiClient.convertToType(data['significantPersonDocuments'], [SignificantPersonDocumentsModel]);
            }
            if (data.hasOwnProperty('bankStatements')) {
                obj['bankStatements'] = ApiClient.convertToType(data['bankStatements'], {'String': KycDocumentModel});
            }
            if (data.hasOwnProperty('leadId')) {
                obj['leadId'] = ApiClient.convertToType(data['leadId'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('companyType')) {
                obj['companyType'] = ApiClient.convertToType(data['companyType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, module:model/KycDocumentModel>} companyDocuments
 */
KycDocumentsV2StepModel.prototype['companyDocuments'] = undefined;

/**
 * Gets or sets a list of YL.Web.Api.ThirdParty.Onboarding.Models.SignificantPersonDocumentsModel
 * @member {Array.<module:model/SignificantPersonDocumentsModel>} significantPersonDocuments
 */
KycDocumentsV2StepModel.prototype['significantPersonDocuments'] = undefined;

/**
 * Gets or sets a Dictionary of Guids to YL.Web.Api.ThirdParty.Onboarding.Models.KycDocumentModel&gt;
 * @member {Object.<String, module:model/KycDocumentModel>} bankStatements
 */
KycDocumentsV2StepModel.prototype['bankStatements'] = undefined;

/**
 * Gets or sets the lead id
 * @member {String} leadId
 */
KycDocumentsV2StepModel.prototype['leadId'] = undefined;

/**
 * Gets or sets the country
 * @member {String} country
 */
KycDocumentsV2StepModel.prototype['country'] = undefined;

/**
 * Gets or sets the company type
 * @member {String} companyType
 */
KycDocumentsV2StepModel.prototype['companyType'] = undefined;






export default KycDocumentsV2StepModel;

