/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The KycDocumentModel model module.
 * @module model/KycDocumentModel
 * @version 1.0
 */
class KycDocumentModel {
    /**
     * Constructs a new <code>KycDocumentModel</code>.
     * Model containing details about a KYC document
     * @alias module:model/KycDocumentModel
     */
    constructor() { 
        
        KycDocumentModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>KycDocumentModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KycDocumentModel} obj Optional instance to populate.
     * @return {module:model/KycDocumentModel} The populated <code>KycDocumentModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KycDocumentModel();

            if (data.hasOwnProperty('documentId')) {
                obj['documentId'] = ApiClient.convertToType(data['documentId'], 'String');
            }
            if (data.hasOwnProperty('documentName')) {
                obj['documentName'] = ApiClient.convertToType(data['documentName'], 'String');
            }
            if (data.hasOwnProperty('documentType')) {
                obj['documentType'] = ApiClient.convertToType(data['documentType'], 'String');
            }
            if (data.hasOwnProperty('kycDocumentType')) {
                obj['kycDocumentType'] = ApiClient.convertToType(data['kycDocumentType'], 'String');
            }
            if (data.hasOwnProperty('dateUploaded')) {
                obj['dateUploaded'] = ApiClient.convertToType(data['dateUploaded'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the document id
 * @member {String} documentId
 */
KycDocumentModel.prototype['documentId'] = undefined;

/**
 * Gets or sets the document name
 * @member {String} documentName
 */
KycDocumentModel.prototype['documentName'] = undefined;

/**
 * Gets or sets the document type (e.g. pdf, csv)
 * @member {String} documentType
 */
KycDocumentModel.prototype['documentType'] = undefined;

/**
 * Gets or sets the KYC document type (e.g. passport, proof of address)
 * @member {String} kycDocumentType
 */
KycDocumentModel.prototype['kycDocumentType'] = undefined;

/**
 * Gets or sets the upload date of the KYC document
 * @member {Date} dateUploaded
 */
KycDocumentModel.prototype['dateUploaded'] = undefined;






export default KycDocumentModel;

