/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import KycQuestions from './KycQuestions';

/**
 * The KycQuestionsStepView model module.
 * @module model/KycQuestionsStepView
 * @version 1.0
 */
class KycQuestionsStepView {
    /**
     * Constructs a new <code>KycQuestionsStepView</code>.
     * @alias module:model/KycQuestionsStepView
     */
    constructor() { 
        
        KycQuestionsStepView.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>KycQuestionsStepView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KycQuestionsStepView} obj Optional instance to populate.
     * @return {module:model/KycQuestionsStepView} The populated <code>KycQuestionsStepView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KycQuestionsStepView();

            if (data.hasOwnProperty('leadId')) {
                obj['leadId'] = ApiClient.convertToType(data['leadId'], 'String');
            }
            if (data.hasOwnProperty('kycQuestions')) {
                obj['kycQuestions'] = KycQuestions.constructFromObject(data['kycQuestions']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} leadId
 */
KycQuestionsStepView.prototype['leadId'] = undefined;

/**
 * @member {module:model/KycQuestions} kycQuestions
 */
KycQuestionsStepView.prototype['kycQuestions'] = undefined;






export default KycQuestionsStepView;

