/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FreeTextQuestionModel from './FreeTextQuestionModel';
import YesNoQuestionModel from './YesNoQuestionModel';

/**
 * The KycQuestionsModel model module.
 * @module model/KycQuestionsModel
 * @version 1.0
 */
class KycQuestionsModel {
    /**
     * Constructs a new <code>KycQuestionsModel</code>.
     * KYC Questions Model for answers to the following questions:  * everTerminated - Has the company ever been terminated or suspended by a payment service provider?  * anyPoliticallyExposedPeople - Are there any Politically Exposed Persons in the management or ownership?  * businessArea - Please indicate the percentage of appropriate business activity the company is involved in (e.g., retail services 100%):  * countriesOperateIn - Please list all countries the business sells their products/services in:  * anyLawEnforcedSanctions - Has the company or parent company been the subject of any money laundering or terrorist financing-related proceedings, investigations, sanctions, punitive actions indictment, had fines, conviction or civil enforcement action imposed on the company or parent company by a regulator or law enforcement body during the last five years?  * anyTerrorismFinancing - Has the company, to your knowledge, been the subject to any investigation, indictment, penalty, fine, conviction or civil enforcement action related to terrorism financing in the past five years?  * anyCriminals - Have the owners/board of directors/CEO ever been convicted of any crime?
     * @alias module:model/KycQuestionsModel
     * @param everTerminated {module:model/YesNoQuestionModel} 
     * @param anyPoliticallyExposedPeople {module:model/YesNoQuestionModel} 
     * @param businessArea {module:model/FreeTextQuestionModel} 
     * @param countriesOperateIn {module:model/FreeTextQuestionModel} 
     * @param anyLawEnforcedSanctions {module:model/YesNoQuestionModel} 
     * @param anyTerrorismFinancing {module:model/YesNoQuestionModel} 
     * @param anyCriminals {module:model/YesNoQuestionModel} 
     */
    constructor(everTerminated, anyPoliticallyExposedPeople, businessArea, countriesOperateIn, anyLawEnforcedSanctions, anyTerrorismFinancing, anyCriminals) { 
        
        KycQuestionsModel.initialize(this, everTerminated, anyPoliticallyExposedPeople, businessArea, countriesOperateIn, anyLawEnforcedSanctions, anyTerrorismFinancing, anyCriminals);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, everTerminated, anyPoliticallyExposedPeople, businessArea, countriesOperateIn, anyLawEnforcedSanctions, anyTerrorismFinancing, anyCriminals) { 
        obj['everTerminated'] = everTerminated;
        obj['anyPoliticallyExposedPeople'] = anyPoliticallyExposedPeople;
        obj['businessArea'] = businessArea;
        obj['countriesOperateIn'] = countriesOperateIn;
        obj['anyLawEnforcedSanctions'] = anyLawEnforcedSanctions;
        obj['anyTerrorismFinancing'] = anyTerrorismFinancing;
        obj['anyCriminals'] = anyCriminals;
    }

    /**
     * Constructs a <code>KycQuestionsModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KycQuestionsModel} obj Optional instance to populate.
     * @return {module:model/KycQuestionsModel} The populated <code>KycQuestionsModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KycQuestionsModel();

            if (data.hasOwnProperty('everTerminated')) {
                obj['everTerminated'] = YesNoQuestionModel.constructFromObject(data['everTerminated']);
            }
            if (data.hasOwnProperty('anyPoliticallyExposedPeople')) {
                obj['anyPoliticallyExposedPeople'] = YesNoQuestionModel.constructFromObject(data['anyPoliticallyExposedPeople']);
            }
            if (data.hasOwnProperty('businessArea')) {
                obj['businessArea'] = FreeTextQuestionModel.constructFromObject(data['businessArea']);
            }
            if (data.hasOwnProperty('countriesOperateIn')) {
                obj['countriesOperateIn'] = FreeTextQuestionModel.constructFromObject(data['countriesOperateIn']);
            }
            if (data.hasOwnProperty('anyLawEnforcedSanctions')) {
                obj['anyLawEnforcedSanctions'] = YesNoQuestionModel.constructFromObject(data['anyLawEnforcedSanctions']);
            }
            if (data.hasOwnProperty('anyTerrorismFinancing')) {
                obj['anyTerrorismFinancing'] = YesNoQuestionModel.constructFromObject(data['anyTerrorismFinancing']);
            }
            if (data.hasOwnProperty('anyCriminals')) {
                obj['anyCriminals'] = YesNoQuestionModel.constructFromObject(data['anyCriminals']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/YesNoQuestionModel} everTerminated
 */
KycQuestionsModel.prototype['everTerminated'] = undefined;

/**
 * @member {module:model/YesNoQuestionModel} anyPoliticallyExposedPeople
 */
KycQuestionsModel.prototype['anyPoliticallyExposedPeople'] = undefined;

/**
 * @member {module:model/FreeTextQuestionModel} businessArea
 */
KycQuestionsModel.prototype['businessArea'] = undefined;

/**
 * @member {module:model/FreeTextQuestionModel} countriesOperateIn
 */
KycQuestionsModel.prototype['countriesOperateIn'] = undefined;

/**
 * @member {module:model/YesNoQuestionModel} anyLawEnforcedSanctions
 */
KycQuestionsModel.prototype['anyLawEnforcedSanctions'] = undefined;

/**
 * @member {module:model/YesNoQuestionModel} anyTerrorismFinancing
 */
KycQuestionsModel.prototype['anyTerrorismFinancing'] = undefined;

/**
 * @member {module:model/YesNoQuestionModel} anyCriminals
 */
KycQuestionsModel.prototype['anyCriminals'] = undefined;






export default KycQuestionsModel;

