/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import KycFreeTextQuestion from './KycFreeTextQuestion';
import KycYesNoQuestion from './KycYesNoQuestion';

/**
 * The KycQuestions model module.
 * @module model/KycQuestions
 * @version 1.0
 */
class KycQuestions {
    /**
     * Constructs a new <code>KycQuestions</code>.
     * @alias module:model/KycQuestions
     */
    constructor() { 
        
        KycQuestions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>KycQuestions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KycQuestions} obj Optional instance to populate.
     * @return {module:model/KycQuestions} The populated <code>KycQuestions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KycQuestions();

            if (data.hasOwnProperty('everTerminated')) {
                obj['everTerminated'] = KycYesNoQuestion.constructFromObject(data['everTerminated']);
            }
            if (data.hasOwnProperty('anyPoliticallyExposedPeople')) {
                obj['anyPoliticallyExposedPeople'] = KycYesNoQuestion.constructFromObject(data['anyPoliticallyExposedPeople']);
            }
            if (data.hasOwnProperty('businessArea')) {
                obj['businessArea'] = KycFreeTextQuestion.constructFromObject(data['businessArea']);
            }
            if (data.hasOwnProperty('countriesOperateIn')) {
                obj['countriesOperateIn'] = KycFreeTextQuestion.constructFromObject(data['countriesOperateIn']);
            }
            if (data.hasOwnProperty('anyLawEnforcedSanctions')) {
                obj['anyLawEnforcedSanctions'] = KycYesNoQuestion.constructFromObject(data['anyLawEnforcedSanctions']);
            }
            if (data.hasOwnProperty('anyTerrorismFinancing')) {
                obj['anyTerrorismFinancing'] = KycYesNoQuestion.constructFromObject(data['anyTerrorismFinancing']);
            }
            if (data.hasOwnProperty('anyCriminals')) {
                obj['anyCriminals'] = KycYesNoQuestion.constructFromObject(data['anyCriminals']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/KycYesNoQuestion} everTerminated
 */
KycQuestions.prototype['everTerminated'] = undefined;

/**
 * @member {module:model/KycYesNoQuestion} anyPoliticallyExposedPeople
 */
KycQuestions.prototype['anyPoliticallyExposedPeople'] = undefined;

/**
 * @member {module:model/KycFreeTextQuestion} businessArea
 */
KycQuestions.prototype['businessArea'] = undefined;

/**
 * @member {module:model/KycFreeTextQuestion} countriesOperateIn
 */
KycQuestions.prototype['countriesOperateIn'] = undefined;

/**
 * @member {module:model/KycYesNoQuestion} anyLawEnforcedSanctions
 */
KycQuestions.prototype['anyLawEnforcedSanctions'] = undefined;

/**
 * @member {module:model/KycYesNoQuestion} anyTerrorismFinancing
 */
KycQuestions.prototype['anyTerrorismFinancing'] = undefined;

/**
 * @member {module:model/KycYesNoQuestion} anyCriminals
 */
KycQuestions.prototype['anyCriminals'] = undefined;






export default KycQuestions;

