/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OnboardingStateModel model module.
 * @module model/OnboardingStateModel
 * @version 1.0
 */
class OnboardingStateModel {
    /**
     * Constructs a new <code>OnboardingStateModel</code>.
     * The model for the onboarding state
     * @alias module:model/OnboardingStateModel
     */
    constructor() { 
        
        OnboardingStateModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OnboardingStateModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OnboardingStateModel} obj Optional instance to populate.
     * @return {module:model/OnboardingStateModel} The populated <code>OnboardingStateModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OnboardingStateModel();

            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the state of the onboarding. Should be one of \"stage1submitted\" or \"stage2submitted\"
 * @member {String} state
 */
OnboardingStateModel.prototype['state'] = undefined;






export default OnboardingStateModel;

