/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AddressModel from './AddressModel';
import Industry from './Industry';
import MerchantIdsModel from './MerchantIdsModel';

/**
 * The OnboardingOrganisationDetailsModel model module.
 * @module model/OnboardingOrganisationDetailsModel
 * @version 1.0
 */
class OnboardingOrganisationDetailsModel {
    /**
     * Constructs a new <code>OnboardingOrganisationDetailsModel</code>.
     * Model for miscellaneous details for a company
     * @alias module:model/OnboardingOrganisationDetailsModel
     */
    constructor() { 
        
        OnboardingOrganisationDetailsModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OnboardingOrganisationDetailsModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OnboardingOrganisationDetailsModel} obj Optional instance to populate.
     * @return {module:model/OnboardingOrganisationDetailsModel} The populated <code>OnboardingOrganisationDetailsModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OnboardingOrganisationDetailsModel();

            if (data.hasOwnProperty('companyName')) {
                obj['companyName'] = ApiClient.convertToType(data['companyName'], 'String');
            }
            if (data.hasOwnProperty('companyNumber')) {
                obj['companyNumber'] = ApiClient.convertToType(data['companyNumber'], 'String');
            }
            if (data.hasOwnProperty('vatNumber')) {
                obj['vatNumber'] = ApiClient.convertToType(data['vatNumber'], 'String');
            }
            if (data.hasOwnProperty('formationDate')) {
                obj['formationDate'] = ApiClient.convertToType(data['formationDate'], 'Date');
            }
            if (data.hasOwnProperty('companyType')) {
                obj['companyType'] = ApiClient.convertToType(data['companyType'], 'String');
            }
            if (data.hasOwnProperty('registeredAddress')) {
                obj['registeredAddress'] = AddressModel.constructFromObject(data['registeredAddress']);
            }
            if (data.hasOwnProperty('countryISOCode')) {
                obj['countryISOCode'] = ApiClient.convertToType(data['countryISOCode'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('industries')) {
                obj['industries'] = ApiClient.convertToType(data['industries'], [Industry]);
            }
            if (data.hasOwnProperty('keyContactName')) {
                obj['keyContactName'] = ApiClient.convertToType(data['keyContactName'], 'String');
            }
            if (data.hasOwnProperty('companyWebsite')) {
                obj['companyWebsite'] = ApiClient.convertToType(data['companyWebsite'], 'String');
            }
            if (data.hasOwnProperty('contactPhoneNumber')) {
                obj['contactPhoneNumber'] = ApiClient.convertToType(data['contactPhoneNumber'], 'String');
            }
            if (data.hasOwnProperty('contactEmailAddress')) {
                obj['contactEmailAddress'] = ApiClient.convertToType(data['contactEmailAddress'], 'String');
            }
            if (data.hasOwnProperty('merchantIds')) {
                obj['merchantIds'] = MerchantIdsModel.constructFromObject(data['merchantIds']);
            }
            if (data.hasOwnProperty('confirmedCreditSearch')) {
                obj['confirmedCreditSearch'] = ApiClient.convertToType(data['confirmedCreditSearch'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the merchant's company name
 * @member {String} companyName
 */
OnboardingOrganisationDetailsModel.prototype['companyName'] = undefined;

/**
 * Gets or sets the registered company number
 * @member {String} companyNumber
 */
OnboardingOrganisationDetailsModel.prototype['companyNumber'] = undefined;

/**
 * Gets or sets the VAT number for the company
 * @member {String} vatNumber
 */
OnboardingOrganisationDetailsModel.prototype['vatNumber'] = undefined;

/**
 * Gets or sets the formation date of the company
 * @member {Date} formationDate
 */
OnboardingOrganisationDetailsModel.prototype['formationDate'] = undefined;

/**
 * Gets or sets the company type
 * @member {String} companyType
 */
OnboardingOrganisationDetailsModel.prototype['companyType'] = undefined;

/**
 * @member {module:model/AddressModel} registeredAddress
 */
OnboardingOrganisationDetailsModel.prototype['registeredAddress'] = undefined;

/**
 * Gets or sets the ISO country code for the company
 * @member {String} countryISOCode
 */
OnboardingOrganisationDetailsModel.prototype['countryISOCode'] = undefined;

/**
 * Gets or sets the description for the company
 * @member {String} description
 */
OnboardingOrganisationDetailsModel.prototype['description'] = undefined;

/**
 * Gets or sets the list of industries that the company conducts business in
 * @member {Array.<module:model/Industry>} industries
 */
OnboardingOrganisationDetailsModel.prototype['industries'] = undefined;

/**
 * Gets or sets the key merchant contact who will be setting up the loan
 * @member {String} keyContactName
 */
OnboardingOrganisationDetailsModel.prototype['keyContactName'] = undefined;

/**
 * Gets or sets the merchant's company website URL
 * @member {String} companyWebsite
 */
OnboardingOrganisationDetailsModel.prototype['companyWebsite'] = undefined;

/**
 * Gets or sets the merchant's contact phone number
 * @member {String} contactPhoneNumber
 */
OnboardingOrganisationDetailsModel.prototype['contactPhoneNumber'] = undefined;

/**
 * Gets or sets the merchant's key contact email address
 * @member {String} contactEmailAddress
 */
OnboardingOrganisationDetailsModel.prototype['contactEmailAddress'] = undefined;

/**
 * @member {module:model/MerchantIdsModel} merchantIds
 */
OnboardingOrganisationDetailsModel.prototype['merchantIds'] = undefined;

/**
 * Gets or sets a value indicating whether the lead has given their consent for a credit search.
 * @member {Boolean} confirmedCreditSearch
 */
OnboardingOrganisationDetailsModel.prototype['confirmedCreditSearch'] = undefined;






export default OnboardingOrganisationDetailsModel;

