/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentGatewayModel model module.
 * @module model/PaymentGatewayModel
 * @version 1.0
 */
class PaymentGatewayModel {
    /**
     * Constructs a new <code>PaymentGatewayModel</code>.
     * Payment Gateway Model
     * @alias module:model/PaymentGatewayModel
     * @param gatewayName {String} Gets or sets the payment gateway name
     */
    constructor(gatewayName) { 
        
        PaymentGatewayModel.initialize(this, gatewayName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, gatewayName) { 
        obj['gatewayName'] = gatewayName;
    }

    /**
     * Constructs a <code>PaymentGatewayModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentGatewayModel} obj Optional instance to populate.
     * @return {module:model/PaymentGatewayModel} The populated <code>PaymentGatewayModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentGatewayModel();

            if (data.hasOwnProperty('gatewayName')) {
                obj['gatewayName'] = ApiClient.convertToType(data['gatewayName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the payment gateway name
 * @member {String} gatewayName
 */
PaymentGatewayModel.prototype['gatewayName'] = undefined;






export default PaymentGatewayModel;

