/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AdvanceSignUpData from './AdvanceSignUpData';
import Document from './Document';

/**
 * The PaymentDataStepView model module.
 * @module model/PaymentDataStepView
 * @version 1.0
 */
class PaymentDataStepView {
    /**
     * Constructs a new <code>PaymentDataStepView</code>.
     * A model containing data about payment data for a lead
     * @alias module:model/PaymentDataStepView
     */
    constructor() { 
        
        PaymentDataStepView.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentDataStepView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentDataStepView} obj Optional instance to populate.
     * @return {module:model/PaymentDataStepView} The populated <code>PaymentDataStepView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentDataStepView();

            if (data.hasOwnProperty('leadId')) {
                obj['leadId'] = ApiClient.convertToType(data['leadId'], 'String');
            }
            if (data.hasOwnProperty('paymentDataDocuments')) {
                obj['paymentDataDocuments'] = ApiClient.convertToType(data['paymentDataDocuments'], {'String': Document});
            }
            if (data.hasOwnProperty('gatewaysUsed')) {
                obj['gatewaysUsed'] = ApiClient.convertToType(data['gatewaysUsed'], ['String']);
            }
            if (data.hasOwnProperty('calculatorData')) {
                obj['calculatorData'] = AdvanceSignUpData.constructFromObject(data['calculatorData']);
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the lead id
 * @member {String} leadId
 */
PaymentDataStepView.prototype['leadId'] = undefined;

/**
 * Gets or sets the dictionary of documents uploaded
 * @member {Object.<String, module:model/Document>} paymentDataDocuments
 */
PaymentDataStepView.prototype['paymentDataDocuments'] = undefined;

/**
 * Gets or sets a list of payment gateways used
 * @member {Array.<String>} gatewaysUsed
 */
PaymentDataStepView.prototype['gatewaysUsed'] = undefined;

/**
 * @member {module:model/AdvanceSignUpData} calculatorData
 */
PaymentDataStepView.prototype['calculatorData'] = undefined;

/**
 * Gets or sets the country
 * @member {String} country
 */
PaymentDataStepView.prototype['country'] = undefined;






export default PaymentDataStepView;

