/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SaveSignificantPersonsResultModel model module.
 * @module model/SaveSignificantPersonsResultModel
 * @version 1.0
 */
class SaveSignificantPersonsResultModel {
    /**
     * Constructs a new <code>SaveSignificantPersonsResultModel</code>.
     * The result of creating a third party lead
     * @alias module:model/SaveSignificantPersonsResultModel
     */
    constructor() { 
        
        SaveSignificantPersonsResultModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SaveSignificantPersonsResultModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SaveSignificantPersonsResultModel} obj Optional instance to populate.
     * @return {module:model/SaveSignificantPersonsResultModel} The populated <code>SaveSignificantPersonsResultModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SaveSignificantPersonsResultModel();

            if (data.hasOwnProperty('leadId')) {
                obj['leadId'] = ApiClient.convertToType(data['leadId'], 'String');
            }
            if (data.hasOwnProperty('significantPersonIds')) {
                obj['significantPersonIds'] = ApiClient.convertToType(data['significantPersonIds'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the Lead Id
 * @member {String} leadId
 */
SaveSignificantPersonsResultModel.prototype['leadId'] = undefined;

/**
 * Gets or sets the Significant person ids
 * @member {Array.<String>} significantPersonIds
 */
SaveSignificantPersonsResultModel.prototype['significantPersonIds'] = undefined;






export default SaveSignificantPersonsResultModel;

