/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SignatorySigningViewModel model module.
 * @module model/SignatorySigningViewModel
 * @version 1.0
 */
class SignatorySigningViewModel {
    /**
     * Constructs a new <code>SignatorySigningViewModel</code>.
     * The view model for a signatory signing
     * @alias module:model/SignatorySigningViewModel
     */
    constructor() { 
        
        SignatorySigningViewModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SignatorySigningViewModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignatorySigningViewModel} obj Optional instance to populate.
     * @return {module:model/SignatorySigningViewModel} The populated <code>SignatorySigningViewModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignatorySigningViewModel();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('recipientStatus')) {
                obj['recipientStatus'] = ApiClient.convertToType(data['recipientStatus'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the name of the signatory
 * @member {String} name
 */
SignatorySigningViewModel.prototype['name'] = undefined;

/**
 * Gets or sets the email of the signatory
 * @member {String} email
 */
SignatorySigningViewModel.prototype['email'] = undefined;

/**
 * Gets or sets the status of the signatory
 * @member {String} recipientStatus
 */
SignatorySigningViewModel.prototype['recipientStatus'] = undefined;






export default SignatorySigningViewModel;

