/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SignificantPersonModel from './SignificantPersonModel';

/**
 * The SignificantPersonsModel model module.
 * @module model/SignificantPersonsModel
 * @version 1.0
 */
class SignificantPersonsModel {
    /**
     * Constructs a new <code>SignificantPersonsModel</code>.
     * Collection of significant persons
     * @alias module:model/SignificantPersonsModel
     * @param significantPersons {Array.<module:model/SignificantPersonModel>} Gets or sets a list of significant persons
     */
    constructor(significantPersons) { 
        
        SignificantPersonsModel.initialize(this, significantPersons);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, significantPersons) { 
        obj['significantPersons'] = significantPersons;
    }

    /**
     * Constructs a <code>SignificantPersonsModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignificantPersonsModel} obj Optional instance to populate.
     * @return {module:model/SignificantPersonsModel} The populated <code>SignificantPersonsModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignificantPersonsModel();

            if (data.hasOwnProperty('significantPersons')) {
                obj['significantPersons'] = ApiClient.convertToType(data['significantPersons'], [SignificantPersonModel]);
            }
        }
        return obj;
    }


}

/**
 * Gets or sets a list of significant persons
 * @member {Array.<module:model/SignificantPersonModel>} significantPersons
 */
SignificantPersonsModel.prototype['significantPersons'] = undefined;






export default SignificantPersonsModel;

