/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import KycDocumentModel from './KycDocumentModel';

/**
 * The SignificantPersonDocumentsModel model module.
 * @module model/SignificantPersonDocumentsModel
 * @version 1.0
 */
class SignificantPersonDocumentsModel {
    /**
     * Constructs a new <code>SignificantPersonDocumentsModel</code>.
     * Model for documents associated with a significant person
     * @alias module:model/SignificantPersonDocumentsModel
     */
    constructor() { 
        
        SignificantPersonDocumentsModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SignificantPersonDocumentsModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignificantPersonDocumentsModel} obj Optional instance to populate.
     * @return {module:model/SignificantPersonDocumentsModel} The populated <code>SignificantPersonDocumentsModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignificantPersonDocumentsModel();

            if (data.hasOwnProperty('personId')) {
                obj['personId'] = ApiClient.convertToType(data['personId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('documents')) {
                obj['documents'] = ApiClient.convertToType(data['documents'], {'String': KycDocumentModel});
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the significant person id
 * @member {String} personId
 */
SignificantPersonDocumentsModel.prototype['personId'] = undefined;

/**
 * Gets or sets the name of the significant person
 * @member {String} name
 */
SignificantPersonDocumentsModel.prototype['name'] = undefined;

/**
 * Gets or sets the dictionary mapping document name to YL.Web.Api.ThirdParty.Onboarding.Models.KycDocumentModel
 * @member {Object.<String, module:model/KycDocumentModel>} documents
 */
SignificantPersonDocumentsModel.prototype['documents'] = undefined;






export default SignificantPersonDocumentsModel;

