/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';

/**
 * The SignificantPersonV2 model module.
 * @module model/SignificantPersonV2
 * @version 1.0
 */
class SignificantPersonV2 {
    /**
     * Constructs a new <code>SignificantPersonV2</code>.
     * @alias module:model/SignificantPersonV2
     */
    constructor() { 
        
        SignificantPersonV2.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SignificantPersonV2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignificantPersonV2} obj Optional instance to populate.
     * @return {module:model/SignificantPersonV2} The populated <code>SignificantPersonV2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignificantPersonV2();

            if (data.hasOwnProperty('personId')) {
                obj['personId'] = ApiClient.convertToType(data['personId'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('surname')) {
                obj['surname'] = ApiClient.convertToType(data['surname'], 'String');
            }
            if (data.hasOwnProperty('typeOfPerson')) {
                obj['typeOfPerson'] = ApiClient.convertToType(data['typeOfPerson'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = Address.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('dateOfBirth')) {
                obj['dateOfBirth'] = ApiClient.convertToType(data['dateOfBirth'], 'Date');
            }
            if (data.hasOwnProperty('percentageOwned')) {
                obj['percentageOwned'] = ApiClient.convertToType(data['percentageOwned'], 'Number');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('mobileNumber')) {
                obj['mobileNumber'] = ApiClient.convertToType(data['mobileNumber'], 'String');
            }
            if (data.hasOwnProperty('nationality')) {
                obj['nationality'] = ApiClient.convertToType(data['nationality'], 'String');
            }
            if (data.hasOwnProperty('niNumber')) {
                obj['niNumber'] = ApiClient.convertToType(data['niNumber'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} personId
 */
SignificantPersonV2.prototype['personId'] = undefined;

/**
 * @member {String} firstName
 */
SignificantPersonV2.prototype['firstName'] = undefined;

/**
 * @member {String} surname
 */
SignificantPersonV2.prototype['surname'] = undefined;

/**
 * @member {String} typeOfPerson
 */
SignificantPersonV2.prototype['typeOfPerson'] = undefined;

/**
 * @member {module:model/Address} address
 */
SignificantPersonV2.prototype['address'] = undefined;

/**
 * @member {Date} dateOfBirth
 */
SignificantPersonV2.prototype['dateOfBirth'] = undefined;

/**
 * @member {Number} percentageOwned
 */
SignificantPersonV2.prototype['percentageOwned'] = undefined;

/**
 * @member {String} email
 */
SignificantPersonV2.prototype['email'] = undefined;

/**
 * @member {String} mobileNumber
 */
SignificantPersonV2.prototype['mobileNumber'] = undefined;

/**
 * @member {String} nationality
 */
SignificantPersonV2.prototype['nationality'] = undefined;

/**
 * @member {String} niNumber
 */
SignificantPersonV2.prototype['niNumber'] = undefined;






export default SignificantPersonV2;

