/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AddressModel from './AddressModel';

/**
 * The ThirdPartyOnboardingModel model module.
 * @module model/ThirdPartyOnboardingModel
 * @version 1.0
 */
class ThirdPartyOnboardingModel {
    /**
     * Constructs a new <code>ThirdPartyOnboardingModel</code>.
     * Third party onboarding model for create a Youlend lead
     * @alias module:model/ThirdPartyOnboardingModel
     * @param thirdPartyCustomerId {String} Gets or sets the third party's id for a merchant
     * @param thirdPartyLeadId {String} Gets or sets the third party's id for this lead
     * @param countryISOCode {String} Gets or sets the ISO country code for the merchant
     * @param loanCurrencyISOCode {String} Gets or sets the ISO currency code for the merchant
     * @param keyContactName {String} Gets or sets the key merchant contact who will be setting up the loan
     * @param companyType {String} Gets or sets the merchant's company type e.g. Ltd, Sole Trader etc
     * @param companyName {String} Gets or sets the merchant's company name
     * @param registeredAddress {module:model/AddressModel} 
     * @param contactPhoneNumber {String} Gets or sets the merchant's contact phone number
     * @param contactEmailAddress {String} Gets or sets the merchant's key contact email address
     */
    constructor(thirdPartyCustomerId, thirdPartyLeadId, countryISOCode, loanCurrencyISOCode, keyContactName, companyType, companyName, registeredAddress, contactPhoneNumber, contactEmailAddress) { 
        
        ThirdPartyOnboardingModel.initialize(this, thirdPartyCustomerId, thirdPartyLeadId, countryISOCode, loanCurrencyISOCode, keyContactName, companyType, companyName, registeredAddress, contactPhoneNumber, contactEmailAddress);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, thirdPartyCustomerId, thirdPartyLeadId, countryISOCode, loanCurrencyISOCode, keyContactName, companyType, companyName, registeredAddress, contactPhoneNumber, contactEmailAddress) { 
        obj['thirdPartyCustomerId'] = thirdPartyCustomerId;
        obj['thirdPartyLeadId'] = thirdPartyLeadId;
        obj['countryISOCode'] = countryISOCode;
        obj['loanCurrencyISOCode'] = loanCurrencyISOCode;
        obj['keyContactName'] = keyContactName;
        obj['companyType'] = companyType;
        obj['companyName'] = companyName;
        obj['registeredAddress'] = registeredAddress;
        obj['contactPhoneNumber'] = contactPhoneNumber;
        obj['contactEmailAddress'] = contactEmailAddress;
    }

    /**
     * Constructs a <code>ThirdPartyOnboardingModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ThirdPartyOnboardingModel} obj Optional instance to populate.
     * @return {module:model/ThirdPartyOnboardingModel} The populated <code>ThirdPartyOnboardingModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThirdPartyOnboardingModel();

            if (data.hasOwnProperty('thirdPartyCustomerId')) {
                obj['thirdPartyCustomerId'] = ApiClient.convertToType(data['thirdPartyCustomerId'], 'String');
            }
            if (data.hasOwnProperty('thirdPartyLeadId')) {
                obj['thirdPartyLeadId'] = ApiClient.convertToType(data['thirdPartyLeadId'], 'String');
            }
            if (data.hasOwnProperty('countryISOCode')) {
                obj['countryISOCode'] = ApiClient.convertToType(data['countryISOCode'], 'String');
            }
            if (data.hasOwnProperty('loanCurrencyISOCode')) {
                obj['loanCurrencyISOCode'] = ApiClient.convertToType(data['loanCurrencyISOCode'], 'String');
            }
            if (data.hasOwnProperty('monthlyCardRevenue')) {
                obj['monthlyCardRevenue'] = ApiClient.convertToType(data['monthlyCardRevenue'], 'Number');
            }
            if (data.hasOwnProperty('numberOfPaymentsPerMonth')) {
                obj['numberOfPaymentsPerMonth'] = ApiClient.convertToType(data['numberOfPaymentsPerMonth'], 'Number');
            }
            if (data.hasOwnProperty('sweepPercentage')) {
                obj['sweepPercentage'] = ApiClient.convertToType(data['sweepPercentage'], 'Number');
            }
            if (data.hasOwnProperty('monthsTrading')) {
                obj['monthsTrading'] = ApiClient.convertToType(data['monthsTrading'], 'Number');
            }
            if (data.hasOwnProperty('loanAmount')) {
                obj['loanAmount'] = ApiClient.convertToType(data['loanAmount'], 'Number');
            }
            if (data.hasOwnProperty('keyContactName')) {
                obj['keyContactName'] = ApiClient.convertToType(data['keyContactName'], 'String');
            }
            if (data.hasOwnProperty('companyType')) {
                obj['companyType'] = ApiClient.convertToType(data['companyType'], 'String');
            }
            if (data.hasOwnProperty('companyName')) {
                obj['companyName'] = ApiClient.convertToType(data['companyName'], 'String');
            }
            if (data.hasOwnProperty('companyWebsite')) {
                obj['companyWebsite'] = ApiClient.convertToType(data['companyWebsite'], 'String');
            }
            if (data.hasOwnProperty('companyNumber')) {
                obj['companyNumber'] = ApiClient.convertToType(data['companyNumber'], 'String');
            }
            if (data.hasOwnProperty('vatNumber')) {
                obj['vatNumber'] = ApiClient.convertToType(data['vatNumber'], 'String');
            }
            if (data.hasOwnProperty('mid')) {
                obj['mid'] = ApiClient.convertToType(data['mid'], 'String');
            }
            if (data.hasOwnProperty('registeredAddress')) {
                obj['registeredAddress'] = AddressModel.constructFromObject(data['registeredAddress']);
            }
            if (data.hasOwnProperty('contactPhoneNumber')) {
                obj['contactPhoneNumber'] = ApiClient.convertToType(data['contactPhoneNumber'], 'String');
            }
            if (data.hasOwnProperty('contactEmailAddress')) {
                obj['contactEmailAddress'] = ApiClient.convertToType(data['contactEmailAddress'], 'String');
            }
            if (data.hasOwnProperty('notificationURL')) {
                obj['notificationURL'] = ApiClient.convertToType(data['notificationURL'], 'String');
            }
            if (data.hasOwnProperty('additionalInfo')) {
                obj['additionalInfo'] = ApiClient.convertToType(data['additionalInfo'], {'String': 'String'});
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the third party's id for a merchant
 * @member {String} thirdPartyCustomerId
 */
ThirdPartyOnboardingModel.prototype['thirdPartyCustomerId'] = undefined;

/**
 * Gets or sets the third party's id for this lead
 * @member {String} thirdPartyLeadId
 */
ThirdPartyOnboardingModel.prototype['thirdPartyLeadId'] = undefined;

/**
 * Gets or sets the ISO country code for the merchant
 * @member {String} countryISOCode
 */
ThirdPartyOnboardingModel.prototype['countryISOCode'] = undefined;

/**
 * Gets or sets the ISO currency code for the merchant
 * @member {String} loanCurrencyISOCode
 */
ThirdPartyOnboardingModel.prototype['loanCurrencyISOCode'] = undefined;

/**
 * Gets or sets the monthly card revenue for the merchant
 * @member {Number} monthlyCardRevenue
 */
ThirdPartyOnboardingModel.prototype['monthlyCardRevenue'] = undefined;

/**
 * Gets or sets the number of payments a merchant has a month
 * @member {Number} numberOfPaymentsPerMonth
 */
ThirdPartyOnboardingModel.prototype['numberOfPaymentsPerMonth'] = undefined;

/**
 * Gets or sets the percentange of transaction amount the merchant wants to use to pay back the loan
 * @member {Number} sweepPercentage
 */
ThirdPartyOnboardingModel.prototype['sweepPercentage'] = undefined;

/**
 * Gets or sets the number of months the merchant has been trading
 * @member {Number} monthsTrading
 */
ThirdPartyOnboardingModel.prototype['monthsTrading'] = undefined;

/**
 * Gets or sets the size of loan the merchant wants
 * @member {Number} loanAmount
 */
ThirdPartyOnboardingModel.prototype['loanAmount'] = undefined;

/**
 * Gets or sets the key merchant contact who will be setting up the loan
 * @member {String} keyContactName
 */
ThirdPartyOnboardingModel.prototype['keyContactName'] = undefined;

/**
 * Gets or sets the merchant's company type e.g. Ltd, Sole Trader etc
 * @member {String} companyType
 */
ThirdPartyOnboardingModel.prototype['companyType'] = undefined;

/**
 * Gets or sets the merchant's company name
 * @member {String} companyName
 */
ThirdPartyOnboardingModel.prototype['companyName'] = undefined;

/**
 * Gets or sets the merchants company website URL
 * @member {String} companyWebsite
 */
ThirdPartyOnboardingModel.prototype['companyWebsite'] = undefined;

/**
 * Gets or sets the registered company number for the merchant
 * @member {String} companyNumber
 */
ThirdPartyOnboardingModel.prototype['companyNumber'] = undefined;

/**
 * Gets or sets the VAT number for the merchant
 * @member {String} vatNumber
 */
ThirdPartyOnboardingModel.prototype['vatNumber'] = undefined;

/**
 * Gets or sets the MID for the merchant
 * @member {String} mid
 */
ThirdPartyOnboardingModel.prototype['mid'] = undefined;

/**
 * @member {module:model/AddressModel} registeredAddress
 */
ThirdPartyOnboardingModel.prototype['registeredAddress'] = undefined;

/**
 * Gets or sets the merchant's contact phone number
 * @member {String} contactPhoneNumber
 */
ThirdPartyOnboardingModel.prototype['contactPhoneNumber'] = undefined;

/**
 * Gets or sets the merchant's key contact email address
 * @member {String} contactEmailAddress
 */
ThirdPartyOnboardingModel.prototype['contactEmailAddress'] = undefined;

/**
 * Gets or sets the third parties notification URL to which YouLend will send status updates
 * @member {String} notificationURL
 */
ThirdPartyOnboardingModel.prototype['notificationURL'] = undefined;

/**
 * Gets or sets a list of key values pairs representing any additional lead data not already covered.
 * @member {Object.<String, String>} additionalInfo
 */
ThirdPartyOnboardingModel.prototype['additionalInfo'] = undefined;






export default ThirdPartyOnboardingModel;

