/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The YesNoQuestionModel model module.
 * @module model/YesNoQuestionModel
 * @version 1.0
 */
class YesNoQuestionModel {
    /**
     * Constructs a new <code>YesNoQuestionModel</code>.
     * Yes No Question Model
     * @alias module:model/YesNoQuestionModel
     * @param answer {Boolean} Gets or sets a value indicating whether the answer to the question is yes or no
     */
    constructor(answer) { 
        
        YesNoQuestionModel.initialize(this, answer);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, answer) { 
        obj['answer'] = answer;
    }

    /**
     * Constructs a <code>YesNoQuestionModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/YesNoQuestionModel} obj Optional instance to populate.
     * @return {module:model/YesNoQuestionModel} The populated <code>YesNoQuestionModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new YesNoQuestionModel();

            if (data.hasOwnProperty('answer')) {
                obj['answer'] = ApiClient.convertToType(data['answer'], 'Boolean');
            }
            if (data.hasOwnProperty('additionalInformation')) {
                obj['additionalInformation'] = ApiClient.convertToType(data['additionalInformation'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets a value indicating whether the answer to the question is yes or no
 * @member {Boolean} answer
 */
YesNoQuestionModel.prototype['answer'] = undefined;

/**
 * Gets or sets additonal information in the answer to the yes no question
 * @member {String} additionalInformation
 */
YesNoQuestionModel.prototype['additionalInformation'] = undefined;






export default YesNoQuestionModel;

