/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AccountDetailsModel from '../model/AccountDetailsModel';
import CreateThirdPartyAdvanceOnboardingResultModel from '../model/CreateThirdPartyAdvanceOnboardingResultModel';
import KycQuestionsModel from '../model/KycQuestionsModel';
import PaymentGatewayModel from '../model/PaymentGatewayModel';
import ProblemDetails from '../model/ProblemDetails';
import SaveBankStatementDocumentResultModel from '../model/SaveBankStatementDocumentResultModel';
import SavePaymentDataDocumentResultModel from '../model/SavePaymentDataDocumentResultModel';
import SaveSignficantPersonKycDocumentResultModel from '../model/SaveSignficantPersonKycDocumentResultModel';
import SaveSignificantPersonsResultModel from '../model/SaveSignificantPersonsResultModel';
import SignificantPersonsModel from '../model/SignificantPersonsModel';
import ThirdPartyOnboardingModel from '../model/ThirdPartyOnboardingModel';

/**
* Leads service.
* @module api/LeadsApi
* @version 1.0
*/
export default class LeadsApi {

    /**
    * Constructs a new LeadsApi. 
    * @alias module:api/LeadsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * An endpoint for adding account details to a lead
     * @param {String} leadId The lead id
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {module:model/AccountDetailsModel} opts.accountDetailsModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    leadsLeadIdAccountdetailsPutWithHttpInfo(leadId, opts) {
      opts = opts || {};
      let postBody = opts['accountDetailsModel'];
      // verify the required parameter 'leadId' is set
      if (leadId === undefined || leadId === null) {
        throw new Error("Missing the required parameter 'leadId' when calling leadsLeadIdAccountdetailsPut");
      }

      let pathParams = {
        'leadId': leadId
      };
      let queryParams = {
      };
      let headerParams = {
        'api-version': opts['apiVersion']
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'application/xml'];
      let returnType = null;
      return this.apiClient.callApi(
        '/Leads/{leadId}/accountdetails', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * An endpoint for adding account details to a lead
     * @param {String} leadId The lead id
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {module:model/AccountDetailsModel} opts.accountDetailsModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    leadsLeadIdAccountdetailsPut(leadId, opts) {
      return this.leadsLeadIdAccountdetailsPutWithHttpInfo(leadId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * An endpoint for adding bank statements to a lead
     * @param {String} leadId The lead id
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {File} opts.file 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SaveBankStatementDocumentResultModel} and HTTP response
     */
    leadsLeadIdDocumentsBankstatementsPostWithHttpInfo(leadId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'leadId' is set
      if (leadId === undefined || leadId === null) {
        throw new Error("Missing the required parameter 'leadId' when calling leadsLeadIdDocumentsBankstatementsPost");
      }

      let pathParams = {
        'leadId': leadId
      };
      let queryParams = {
      };
      let headerParams = {
        'api-version': opts['apiVersion']
      };
      let formParams = {
        'file': opts['file']
      };

      let authNames = ['oauth2'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json', 'application/xml'];
      let returnType = SaveBankStatementDocumentResultModel;
      return this.apiClient.callApi(
        '/Leads/{leadId}/documents/bankstatements', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * An endpoint for adding bank statements to a lead
     * @param {String} leadId The lead id
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {File} opts.file 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SaveBankStatementDocumentResultModel}
     */
    leadsLeadIdDocumentsBankstatementsPost(leadId, opts) {
      return this.leadsLeadIdDocumentsBankstatementsPostWithHttpInfo(leadId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * An endpoint for adding payment data documents to a lead
     * @param {String} leadId The lead id
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {File} opts.file 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SavePaymentDataDocumentResultModel} and HTTP response
     */
    leadsLeadIdDocumentsPaymentdataPostWithHttpInfo(leadId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'leadId' is set
      if (leadId === undefined || leadId === null) {
        throw new Error("Missing the required parameter 'leadId' when calling leadsLeadIdDocumentsPaymentdataPost");
      }

      let pathParams = {
        'leadId': leadId
      };
      let queryParams = {
      };
      let headerParams = {
        'api-version': opts['apiVersion']
      };
      let formParams = {
        'file': opts['file']
      };

      let authNames = ['oauth2'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json', 'application/xml'];
      let returnType = SavePaymentDataDocumentResultModel;
      return this.apiClient.callApi(
        '/Leads/{leadId}/documents/paymentdata', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * An endpoint for adding payment data documents to a lead
     * @param {String} leadId The lead id
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {File} opts.file 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SavePaymentDataDocumentResultModel}
     */
    leadsLeadIdDocumentsPaymentdataPost(leadId, opts) {
      return this.leadsLeadIdDocumentsPaymentdataPostWithHttpInfo(leadId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * An endpoint for adding kyc documents for a significant person
     * @param {String} leadId The lead id
     * @param {String} significantPersonId The third party significant person id
     * @param {String} kycDocumentType The kyc document type (passport, proofOfAddress)
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {File} opts.file 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SaveSignficantPersonKycDocumentResultModel} and HTTP response
     */
    leadsLeadIdDocumentsSignificantpersonsSignificantPersonIdKycDocumentTypePostWithHttpInfo(leadId, significantPersonId, kycDocumentType, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'leadId' is set
      if (leadId === undefined || leadId === null) {
        throw new Error("Missing the required parameter 'leadId' when calling leadsLeadIdDocumentsSignificantpersonsSignificantPersonIdKycDocumentTypePost");
      }
      // verify the required parameter 'significantPersonId' is set
      if (significantPersonId === undefined || significantPersonId === null) {
        throw new Error("Missing the required parameter 'significantPersonId' when calling leadsLeadIdDocumentsSignificantpersonsSignificantPersonIdKycDocumentTypePost");
      }
      // verify the required parameter 'kycDocumentType' is set
      if (kycDocumentType === undefined || kycDocumentType === null) {
        throw new Error("Missing the required parameter 'kycDocumentType' when calling leadsLeadIdDocumentsSignificantpersonsSignificantPersonIdKycDocumentTypePost");
      }

      let pathParams = {
        'leadId': leadId,
        'significantPersonId': significantPersonId,
        'kycDocumentType': kycDocumentType
      };
      let queryParams = {
      };
      let headerParams = {
        'api-version': opts['apiVersion']
      };
      let formParams = {
        'file': opts['file']
      };

      let authNames = ['oauth2'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json', 'application/xml'];
      let returnType = SaveSignficantPersonKycDocumentResultModel;
      return this.apiClient.callApi(
        '/Leads/{leadId}/documents/significantpersons/{significantPersonId}/{kycDocumentType}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * An endpoint for adding kyc documents for a significant person
     * @param {String} leadId The lead id
     * @param {String} significantPersonId The third party significant person id
     * @param {String} kycDocumentType The kyc document type (passport, proofOfAddress)
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {File} opts.file 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SaveSignficantPersonKycDocumentResultModel}
     */
    leadsLeadIdDocumentsSignificantpersonsSignificantPersonIdKycDocumentTypePost(leadId, significantPersonId, kycDocumentType, opts) {
      return this.leadsLeadIdDocumentsSignificantpersonsSignificantPersonIdKycDocumentTypePostWithHttpInfo(leadId, significantPersonId, kycDocumentType, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * An endpoint for adding KYC question answers to a lead
     * @param {String} leadId The lead id
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {module:model/KycQuestionsModel} opts.kycQuestionsModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    leadsLeadIdKycquestionsPutWithHttpInfo(leadId, opts) {
      opts = opts || {};
      let postBody = opts['kycQuestionsModel'];
      // verify the required parameter 'leadId' is set
      if (leadId === undefined || leadId === null) {
        throw new Error("Missing the required parameter 'leadId' when calling leadsLeadIdKycquestionsPut");
      }

      let pathParams = {
        'leadId': leadId
      };
      let queryParams = {
      };
      let headerParams = {
        'api-version': opts['apiVersion']
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'application/xml'];
      let returnType = null;
      return this.apiClient.callApi(
        '/Leads/{leadId}/kycquestions', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * An endpoint for adding KYC question answers to a lead
     * @param {String} leadId The lead id
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {module:model/KycQuestionsModel} opts.kycQuestionsModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    leadsLeadIdKycquestionsPut(leadId, opts) {
      return this.leadsLeadIdKycquestionsPutWithHttpInfo(leadId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * An endpoint for adding a payment gateway to a lead
     * @param {String} leadId The lead id
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {module:model/PaymentGatewayModel} opts.paymentGatewayModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    leadsLeadIdPaymentgatewaysPostWithHttpInfo(leadId, opts) {
      opts = opts || {};
      let postBody = opts['paymentGatewayModel'];
      // verify the required parameter 'leadId' is set
      if (leadId === undefined || leadId === null) {
        throw new Error("Missing the required parameter 'leadId' when calling leadsLeadIdPaymentgatewaysPost");
      }

      let pathParams = {
        'leadId': leadId
      };
      let queryParams = {
      };
      let headerParams = {
        'api-version': opts['apiVersion']
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'application/xml'];
      let returnType = null;
      return this.apiClient.callApi(
        '/Leads/{leadId}/paymentgateways', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * An endpoint for adding a payment gateway to a lead
     * @param {String} leadId The lead id
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {module:model/PaymentGatewayModel} opts.paymentGatewayModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    leadsLeadIdPaymentgatewaysPost(leadId, opts) {
      return this.leadsLeadIdPaymentgatewaysPostWithHttpInfo(leadId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * An endpoint for updating significant persons for a lead
     * @param {String} leadId The lead id
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {module:model/SignificantPersonsModel} opts.significantPersonsModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SaveSignificantPersonsResultModel} and HTTP response
     */
    leadsLeadIdSignificantpersonsPutWithHttpInfo(leadId, opts) {
      opts = opts || {};
      let postBody = opts['significantPersonsModel'];
      // verify the required parameter 'leadId' is set
      if (leadId === undefined || leadId === null) {
        throw new Error("Missing the required parameter 'leadId' when calling leadsLeadIdSignificantpersonsPut");
      }

      let pathParams = {
        'leadId': leadId
      };
      let queryParams = {
      };
      let headerParams = {
        'api-version': opts['apiVersion']
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'application/xml'];
      let returnType = SaveSignificantPersonsResultModel;
      return this.apiClient.callApi(
        '/Leads/{leadId}/significantpersons', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * An endpoint for updating significant persons for a lead
     * @param {String} leadId The lead id
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {module:model/SignificantPersonsModel} opts.significantPersonsModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SaveSignificantPersonsResultModel}
     */
    leadsLeadIdSignificantpersonsPut(leadId, opts) {
      return this.leadsLeadIdSignificantpersonsPutWithHttpInfo(leadId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Creates a Youlend Advance Lead
     * Can add sample as an example here
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {module:model/ThirdPartyOnboardingModel} opts.thirdPartyOnboardingModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CreateThirdPartyAdvanceOnboardingResultModel} and HTTP response
     */
    leadsPostWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['thirdPartyOnboardingModel'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'api-version': opts['apiVersion']
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'application/xml'];
      let returnType = CreateThirdPartyAdvanceOnboardingResultModel;
      return this.apiClient.callApi(
        '/Leads', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Creates a Youlend Advance Lead
     * Can add sample as an example here
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiVersion 
     * @param {module:model/ThirdPartyOnboardingModel} opts.thirdPartyOnboardingModel 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CreateThirdPartyAdvanceOnboardingResultModel}
     */
    leadsPost(opts) {
      return this.leadsPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
