/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyOnboardingApiClient);
  }
}(this, function(expect, YlThirdPartyOnboardingApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyOnboardingApiClient.AdvanceSignUpData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdvanceSignUpData', function() {
    it('should create an instance of AdvanceSignUpData', function() {
      // uncomment below and update the code to test AdvanceSignUpData
      //var instane = new YlThirdPartyOnboardingApiClient.AdvanceSignUpData();
      //expect(instance).to.be.a(YlThirdPartyOnboardingApiClient.AdvanceSignUpData);
    });

    it('should have the property currencyISOCode (base name: "currencyISOCode")', function() {
      // uncomment below and update the code to test the property currencyISOCode
      //var instane = new YlThirdPartyOnboardingApiClient.AdvanceSignUpData();
      //expect(instance).to.be();
    });

    it('should have the property monthlyRevenue (base name: "monthlyRevenue")', function() {
      // uncomment below and update the code to test the property monthlyRevenue
      //var instane = new YlThirdPartyOnboardingApiClient.AdvanceSignUpData();
      //expect(instance).to.be();
    });

    it('should have the property monthlyRevenueSliderIndex (base name: "monthlyRevenueSliderIndex")', function() {
      // uncomment below and update the code to test the property monthlyRevenueSliderIndex
      //var instane = new YlThirdPartyOnboardingApiClient.AdvanceSignUpData();
      //expect(instance).to.be();
    });

    it('should have the property numberOfPaymentsPerMonth (base name: "numberOfPaymentsPerMonth")', function() {
      // uncomment below and update the code to test the property numberOfPaymentsPerMonth
      //var instane = new YlThirdPartyOnboardingApiClient.AdvanceSignUpData();
      //expect(instance).to.be();
    });

    it('should have the property numberOfPaymentsPerMonthSliderIndex (base name: "numberOfPaymentsPerMonthSliderIndex")', function() {
      // uncomment below and update the code to test the property numberOfPaymentsPerMonthSliderIndex
      //var instane = new YlThirdPartyOnboardingApiClient.AdvanceSignUpData();
      //expect(instance).to.be();
    });

    it('should have the property sweepPercentage (base name: "sweepPercentage")', function() {
      // uncomment below and update the code to test the property sweepPercentage
      //var instane = new YlThirdPartyOnboardingApiClient.AdvanceSignUpData();
      //expect(instance).to.be();
    });

    it('should have the property timeOperating (base name: "timeOperating")', function() {
      // uncomment below and update the code to test the property timeOperating
      //var instane = new YlThirdPartyOnboardingApiClient.AdvanceSignUpData();
      //expect(instance).to.be();
    });

    it('should have the property timeOperatingSliderIndex (base name: "timeOperatingSliderIndex")', function() {
      // uncomment below and update the code to test the property timeOperatingSliderIndex
      //var instane = new YlThirdPartyOnboardingApiClient.AdvanceSignUpData();
      //expect(instance).to.be();
    });

    it('should have the property sizeOfAdvance (base name: "sizeOfAdvance")', function() {
      // uncomment below and update the code to test the property sizeOfAdvance
      //var instane = new YlThirdPartyOnboardingApiClient.AdvanceSignUpData();
      //expect(instance).to.be();
    });

    it('should have the property sizeOfAdvanceSliderIndex (base name: "sizeOfAdvanceSliderIndex")', function() {
      // uncomment below and update the code to test the property sizeOfAdvanceSliderIndex
      //var instane = new YlThirdPartyOnboardingApiClient.AdvanceSignUpData();
      //expect(instance).to.be();
    });

    it('should have the property howMuchToPayBack (base name: "howMuchToPayBack")', function() {
      // uncomment below and update the code to test the property howMuchToPayBack
      //var instane = new YlThirdPartyOnboardingApiClient.AdvanceSignUpData();
      //expect(instance).to.be();
    });

    it('should have the property payBackInMonths (base name: "payBackInMonths")', function() {
      // uncomment below and update the code to test the property payBackInMonths
      //var instane = new YlThirdPartyOnboardingApiClient.AdvanceSignUpData();
      //expect(instance).to.be();
    });

  });

}));
