/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyOnboardingApiClient);
  }
}(this, function(expect, YlThirdPartyOnboardingApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyOnboardingApiClient.CreditRatingBandParameters();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreditRatingBandParameters', function() {
    it('should create an instance of CreditRatingBandParameters', function() {
      // uncomment below and update the code to test CreditRatingBandParameters
      //var instane = new YlThirdPartyOnboardingApiClient.CreditRatingBandParameters();
      //expect(instance).to.be.a(YlThirdPartyOnboardingApiClient.CreditRatingBandParameters);
    });

    it('should have the property rating (base name: "rating")', function() {
      // uncomment below and update the code to test the property rating
      //var instane = new YlThirdPartyOnboardingApiClient.CreditRatingBandParameters();
      //expect(instance).to.be();
    });

    it('should have the property lowerLimit (base name: "lowerLimit")', function() {
      // uncomment below and update the code to test the property lowerLimit
      //var instane = new YlThirdPartyOnboardingApiClient.CreditRatingBandParameters();
      //expect(instance).to.be();
    });

    it('should have the property upperLimit (base name: "upperLimit")', function() {
      // uncomment below and update the code to test the property upperLimit
      //var instane = new YlThirdPartyOnboardingApiClient.CreditRatingBandParameters();
      //expect(instance).to.be();
    });

    it('should have the property targetTerm (base name: "targetTerm")', function() {
      // uncomment below and update the code to test the property targetTerm
      //var instane = new YlThirdPartyOnboardingApiClient.CreditRatingBandParameters();
      //expect(instance).to.be();
    });

    it('should have the property fee (base name: "fee")', function() {
      // uncomment below and update the code to test the property fee
      //var instane = new YlThirdPartyOnboardingApiClient.CreditRatingBandParameters();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instane = new YlThirdPartyOnboardingApiClient.CreditRatingBandParameters();
      //expect(instance).to.be();
    });

    it('should have the property countryCode (base name: "countryCode")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instane = new YlThirdPartyOnboardingApiClient.CreditRatingBandParameters();
      //expect(instance).to.be();
    });

    it('should have the property loanSweep2 (base name: "loanSweep2")', function() {
      // uncomment below and update the code to test the property loanSweep2
      //var instane = new YlThirdPartyOnboardingApiClient.CreditRatingBandParameters();
      //expect(instance).to.be();
    });

    it('should have the property loanSweep3 (base name: "loanSweep3")', function() {
      // uncomment below and update the code to test the property loanSweep3
      //var instane = new YlThirdPartyOnboardingApiClient.CreditRatingBandParameters();
      //expect(instance).to.be();
    });

  });

}));
