/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyOnboardingApiClient);
  }
}(this, function(expect, YlThirdPartyOnboardingApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyOnboardingApiClient.KycDocumentsV2StepModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('KycDocumentsV2StepModel', function() {
    it('should create an instance of KycDocumentsV2StepModel', function() {
      // uncomment below and update the code to test KycDocumentsV2StepModel
      //var instane = new YlThirdPartyOnboardingApiClient.KycDocumentsV2StepModel();
      //expect(instance).to.be.a(YlThirdPartyOnboardingApiClient.KycDocumentsV2StepModel);
    });

    it('should have the property companyDocuments (base name: "companyDocuments")', function() {
      // uncomment below and update the code to test the property companyDocuments
      //var instane = new YlThirdPartyOnboardingApiClient.KycDocumentsV2StepModel();
      //expect(instance).to.be();
    });

    it('should have the property significantPersonDocuments (base name: "significantPersonDocuments")', function() {
      // uncomment below and update the code to test the property significantPersonDocuments
      //var instane = new YlThirdPartyOnboardingApiClient.KycDocumentsV2StepModel();
      //expect(instance).to.be();
    });

    it('should have the property bankStatements (base name: "bankStatements")', function() {
      // uncomment below and update the code to test the property bankStatements
      //var instane = new YlThirdPartyOnboardingApiClient.KycDocumentsV2StepModel();
      //expect(instance).to.be();
    });

    it('should have the property leadId (base name: "leadId")', function() {
      // uncomment below and update the code to test the property leadId
      //var instane = new YlThirdPartyOnboardingApiClient.KycDocumentsV2StepModel();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instane = new YlThirdPartyOnboardingApiClient.KycDocumentsV2StepModel();
      //expect(instance).to.be();
    });

    it('should have the property companyType (base name: "companyType")', function() {
      // uncomment below and update the code to test the property companyType
      //var instane = new YlThirdPartyOnboardingApiClient.KycDocumentsV2StepModel();
      //expect(instance).to.be();
    });

  });

}));
