/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyOnboardingApiClient);
  }
}(this, function(expect, YlThirdPartyOnboardingApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyOnboardingApiClient.KycQuestionsModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('KycQuestionsModel', function() {
    it('should create an instance of KycQuestionsModel', function() {
      // uncomment below and update the code to test KycQuestionsModel
      //var instane = new YlThirdPartyOnboardingApiClient.KycQuestionsModel();
      //expect(instance).to.be.a(YlThirdPartyOnboardingApiClient.KycQuestionsModel);
    });

    it('should have the property everTerminated (base name: "everTerminated")', function() {
      // uncomment below and update the code to test the property everTerminated
      //var instane = new YlThirdPartyOnboardingApiClient.KycQuestionsModel();
      //expect(instance).to.be();
    });

    it('should have the property anyPoliticallyExposedPeople (base name: "anyPoliticallyExposedPeople")', function() {
      // uncomment below and update the code to test the property anyPoliticallyExposedPeople
      //var instane = new YlThirdPartyOnboardingApiClient.KycQuestionsModel();
      //expect(instance).to.be();
    });

    it('should have the property businessArea (base name: "businessArea")', function() {
      // uncomment below and update the code to test the property businessArea
      //var instane = new YlThirdPartyOnboardingApiClient.KycQuestionsModel();
      //expect(instance).to.be();
    });

    it('should have the property countriesOperateIn (base name: "countriesOperateIn")', function() {
      // uncomment below and update the code to test the property countriesOperateIn
      //var instane = new YlThirdPartyOnboardingApiClient.KycQuestionsModel();
      //expect(instance).to.be();
    });

    it('should have the property anyLawEnforcedSanctions (base name: "anyLawEnforcedSanctions")', function() {
      // uncomment below and update the code to test the property anyLawEnforcedSanctions
      //var instane = new YlThirdPartyOnboardingApiClient.KycQuestionsModel();
      //expect(instance).to.be();
    });

    it('should have the property anyTerrorismFinancing (base name: "anyTerrorismFinancing")', function() {
      // uncomment below and update the code to test the property anyTerrorismFinancing
      //var instane = new YlThirdPartyOnboardingApiClient.KycQuestionsModel();
      //expect(instance).to.be();
    });

    it('should have the property anyCriminals (base name: "anyCriminals")', function() {
      // uncomment below and update the code to test the property anyCriminals
      //var instane = new YlThirdPartyOnboardingApiClient.KycQuestionsModel();
      //expect(instance).to.be();
    });

  });

}));
