/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyOnboardingApiClient);
  }
}(this, function(expect, YlThirdPartyOnboardingApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyOnboardingApiClient.LoanSizingModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LoanSizingModel', function() {
    it('should create an instance of LoanSizingModel', function() {
      // uncomment below and update the code to test LoanSizingModel
      //var instane = new YlThirdPartyOnboardingApiClient.LoanSizingModel();
      //expect(instance).to.be.a(YlThirdPartyOnboardingApiClient.LoanSizingModel);
    });

    it('should have the property loanSizingProcessId (base name: "loanSizingProcessId")', function() {
      // uncomment below and update the code to test the property loanSizingProcessId
      //var instane = new YlThirdPartyOnboardingApiClient.LoanSizingModel();
      //expect(instance).to.be();
    });

    it('should have the property companyNumber (base name: "companyNumber")', function() {
      // uncomment below and update the code to test the property companyNumber
      //var instane = new YlThirdPartyOnboardingApiClient.LoanSizingModel();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "companyName")', function() {
      // uncomment below and update the code to test the property companyName
      //var instane = new YlThirdPartyOnboardingApiClient.LoanSizingModel();
      //expect(instance).to.be();
    });

    it('should have the property averageMonthlyRevenue (base name: "averageMonthlyRevenue")', function() {
      // uncomment below and update the code to test the property averageMonthlyRevenue
      //var instane = new YlThirdPartyOnboardingApiClient.LoanSizingModel();
      //expect(instance).to.be();
    });

    it('should have the property creditRatingBandParameters (base name: "creditRatingBandParameters")', function() {
      // uncomment below and update the code to test the property creditRatingBandParameters
      //var instane = new YlThirdPartyOnboardingApiClient.LoanSizingModel();
      //expect(instance).to.be();
    });

    it('should have the property loanOption1 (base name: "loanOption1")', function() {
      // uncomment below and update the code to test the property loanOption1
      //var instane = new YlThirdPartyOnboardingApiClient.LoanSizingModel();
      //expect(instance).to.be();
    });

    it('should have the property loanOption2 (base name: "loanOption2")', function() {
      // uncomment below and update the code to test the property loanOption2
      //var instane = new YlThirdPartyOnboardingApiClient.LoanSizingModel();
      //expect(instance).to.be();
    });

    it('should have the property loanOption3 (base name: "loanOption3")', function() {
      // uncomment below and update the code to test the property loanOption3
      //var instane = new YlThirdPartyOnboardingApiClient.LoanSizingModel();
      //expect(instance).to.be();
    });

  });

}));
