/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyOnboardingApiClient);
  }
}(this, function(expect, YlThirdPartyOnboardingApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OnboardingOrganisationDetailsModel', function() {
    it('should create an instance of OnboardingOrganisationDetailsModel', function() {
      // uncomment below and update the code to test OnboardingOrganisationDetailsModel
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be.a(YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel);
    });

    it('should have the property companyName (base name: "companyName")', function() {
      // uncomment below and update the code to test the property companyName
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property companyNumber (base name: "companyNumber")', function() {
      // uncomment below and update the code to test the property companyNumber
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property vatNumber (base name: "vatNumber")', function() {
      // uncomment below and update the code to test the property vatNumber
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property formationDate (base name: "formationDate")', function() {
      // uncomment below and update the code to test the property formationDate
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property companyType (base name: "companyType")', function() {
      // uncomment below and update the code to test the property companyType
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property registeredAddress (base name: "registeredAddress")', function() {
      // uncomment below and update the code to test the property registeredAddress
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property countryISOCode (base name: "countryISOCode")', function() {
      // uncomment below and update the code to test the property countryISOCode
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property industries (base name: "industries")', function() {
      // uncomment below and update the code to test the property industries
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property keyContactName (base name: "keyContactName")', function() {
      // uncomment below and update the code to test the property keyContactName
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property companyWebsite (base name: "companyWebsite")', function() {
      // uncomment below and update the code to test the property companyWebsite
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property contactPhoneNumber (base name: "contactPhoneNumber")', function() {
      // uncomment below and update the code to test the property contactPhoneNumber
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property contactEmailAddress (base name: "contactEmailAddress")', function() {
      // uncomment below and update the code to test the property contactEmailAddress
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property merchantIds (base name: "merchantIds")', function() {
      // uncomment below and update the code to test the property merchantIds
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property confirmedCreditSearch (base name: "confirmedCreditSearch")', function() {
      // uncomment below and update the code to test the property confirmedCreditSearch
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingOrganisationDetailsModel();
      //expect(instance).to.be();
    });

  });

}));
