/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyOnboardingApiClient);
  }
}(this, function(expect, YlThirdPartyOnboardingApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyOnboardingApiClient.OnboardingV2View();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OnboardingV2View', function() {
    it('should create an instance of OnboardingV2View', function() {
      // uncomment below and update the code to test OnboardingV2View
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingV2View();
      //expect(instance).to.be.a(YlThirdPartyOnboardingApiClient.OnboardingV2View);
    });

    it('should have the property leadSourceLendingPartnerId (base name: "leadSourceLendingPartnerId")', function() {
      // uncomment below and update the code to test the property leadSourceLendingPartnerId
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingV2View();
      //expect(instance).to.be();
    });

    it('should have the property onboardingState (base name: "onboardingState")', function() {
      // uncomment below and update the code to test the property onboardingState
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingV2View();
      //expect(instance).to.be();
    });

    it('should have the property onboardingStateReason (base name: "onboardingStateReason")', function() {
      // uncomment below and update the code to test the property onboardingStateReason
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingV2View();
      //expect(instance).to.be();
    });

    it('should have the property organisationDetailsStepComplete (base name: "organisationDetailsStepComplete")', function() {
      // uncomment below and update the code to test the property organisationDetailsStepComplete
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingV2View();
      //expect(instance).to.be();
    });

    it('should have the property paymentDataStepComplete (base name: "paymentDataStepComplete")', function() {
      // uncomment below and update the code to test the property paymentDataStepComplete
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingV2View();
      //expect(instance).to.be();
    });

    it('should have the property offerStepComplete (base name: "offerStepComplete")', function() {
      // uncomment below and update the code to test the property offerStepComplete
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingV2View();
      //expect(instance).to.be();
    });

    it('should have the property kycQuestionsStepComplete (base name: "kycQuestionsStepComplete")', function() {
      // uncomment below and update the code to test the property kycQuestionsStepComplete
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingV2View();
      //expect(instance).to.be();
    });

    it('should have the property kycDocumentsStepComplete (base name: "kycDocumentsStepComplete")', function() {
      // uncomment below and update the code to test the property kycDocumentsStepComplete
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingV2View();
      //expect(instance).to.be();
    });

    it('should have the property accountStepComplete (base name: "accountStepComplete")', function() {
      // uncomment below and update the code to test the property accountStepComplete
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingV2View();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "companyName")', function() {
      // uncomment below and update the code to test the property companyName
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingV2View();
      //expect(instance).to.be();
    });

    it('should have the property leadType (base name: "leadType")', function() {
      // uncomment below and update the code to test the property leadType
      //var instane = new YlThirdPartyOnboardingApiClient.OnboardingV2View();
      //expect(instance).to.be();
    });

  });

}));
