/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyOnboardingApiClient);
  }
}(this, function(expect, YlThirdPartyOnboardingApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrganisationDetailsV3', function() {
    it('should create an instance of OrganisationDetailsV3', function() {
      // uncomment below and update the code to test OrganisationDetailsV3
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be.a(YlThirdPartyOnboardingApiClient.OrganisationDetailsV3);
    });

    it('should have the property leadId (base name: "leadId")', function() {
      // uncomment below and update the code to test the property leadId
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "companyName")', function() {
      // uncomment below and update the code to test the property companyName
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property companyNumber (base name: "companyNumber")', function() {
      // uncomment below and update the code to test the property companyNumber
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property vatNumber (base name: "vatNumber")', function() {
      // uncomment below and update the code to test the property vatNumber
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property formationDate (base name: "formationDate")', function() {
      // uncomment below and update the code to test the property formationDate
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property companyType (base name: "companyType")', function() {
      // uncomment below and update the code to test the property companyType
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property keyContactName (base name: "keyContactName")', function() {
      // uncomment below and update the code to test the property keyContactName
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property website (base name: "website")', function() {
      // uncomment below and update the code to test the property website
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property phoneNumber (base name: "phoneNumber")', function() {
      // uncomment below and update the code to test the property phoneNumber
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property significantPersons (base name: "significantPersons")', function() {
      // uncomment below and update the code to test the property significantPersons
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property industries (base name: "industries")', function() {
      // uncomment below and update the code to test the property industries
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

    it('should have the property confirmedCreditSearch (base name: "confirmedCreditSearch")', function() {
      // uncomment below and update the code to test the property confirmedCreditSearch
      //var instane = new YlThirdPartyOnboardingApiClient.OrganisationDetailsV3();
      //expect(instance).to.be();
    });

  });

}));
