/**
 * YouLend Third Party Onboarding API
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YouLendThirdPartyOnboardingApi);
  }
}(this, function(expect, YouLendThirdPartyOnboardingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YouLendThirdPartyOnboardingApi.LeadsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LeadsApi', function() {
    describe('leadsLeadIdAccountdetailsPut', function() {
      it('should call leadsLeadIdAccountdetailsPut successfully', function(done) {
        //uncomment below and update the code to test leadsLeadIdAccountdetailsPut
        //instance.leadsLeadIdAccountdetailsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadsLeadIdDocumentsBankstatementsPost', function() {
      it('should call leadsLeadIdDocumentsBankstatementsPost successfully', function(done) {
        //uncomment below and update the code to test leadsLeadIdDocumentsBankstatementsPost
        //instance.leadsLeadIdDocumentsBankstatementsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadsLeadIdDocumentsPaymentdataPost', function() {
      it('should call leadsLeadIdDocumentsPaymentdataPost successfully', function(done) {
        //uncomment below and update the code to test leadsLeadIdDocumentsPaymentdataPost
        //instance.leadsLeadIdDocumentsPaymentdataPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadsLeadIdDocumentsSignificantpersonsSignificantPersonIdKycDocumentTypePost', function() {
      it('should call leadsLeadIdDocumentsSignificantpersonsSignificantPersonIdKycDocumentTypePost successfully', function(done) {
        //uncomment below and update the code to test leadsLeadIdDocumentsSignificantpersonsSignificantPersonIdKycDocumentTypePost
        //instance.leadsLeadIdDocumentsSignificantpersonsSignificantPersonIdKycDocumentTypePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadsLeadIdKycquestionsPut', function() {
      it('should call leadsLeadIdKycquestionsPut successfully', function(done) {
        //uncomment below and update the code to test leadsLeadIdKycquestionsPut
        //instance.leadsLeadIdKycquestionsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadsLeadIdPaymentgatewaysPost', function() {
      it('should call leadsLeadIdPaymentgatewaysPost successfully', function(done) {
        //uncomment below and update the code to test leadsLeadIdPaymentgatewaysPost
        //instance.leadsLeadIdPaymentgatewaysPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadsLeadIdSignificantpersonsPut', function() {
      it('should call leadsLeadIdSignificantpersonsPut successfully', function(done) {
        //uncomment below and update the code to test leadsLeadIdSignificantpersonsPut
        //instance.leadsLeadIdSignificantpersonsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadsPost', function() {
      it('should call leadsPost successfully', function(done) {
        //uncomment below and update the code to test leadsPost
        //instance.leadsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
